podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    metadata:
      namespace: staging
    spec:
      containers:
      - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      #restartPolicy: Never
      - name: cloud-sdk
        image: google/cloud-sdk
        command:
        - sleep
        args:
        - 9999999
      volumeMounts:
      - name: shared-storage
        mountPath: /mnt
      - name: google-cloud-key
        mountPath: /var/secrets/google
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/umls23-1fd328cc3b0f.json
    restartPolicy: Never
    volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: jenkins-pv-claim
    - name: google-cloud-key
      secret:
        secretName: sdk-key
''') {
  node(POD_LABEL) {

    stage('Deploying to prod') {
      container('cloud-sdk') {
        stage('Build a gradle project') {
          sh '''
          echo 'namespaces in the staging environment'
          kubectl get ns
          gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud container clusters get-credentials umls23 --region us-east1 --project umls23-381716
          echo 'namespaces in the prod environment'
          kubectl get ns
          '''
        }
      }
    }





    stage('Deploy Calculator') {
      git branch: 'main', url: 'https://github.com/jstmarie/week9.git'
      container('gradle') {

        stage('start calculator') {
          sh '''
          cd Ex1
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          ./kubectl apply -f calculator.yaml
          ./kubectl apply -f hazelcast.yaml
          '''
        }

        stage('test sum command') {
          sh '''
          sleep 5
          /usr/bin/test $(curl calculator-service.staging.svc.cluster.local:8080/sum?a=6\\&b=2) -eq 8 && echo '6+2=8 - pass' || '6+2!=8 fail'
          '''
        }

        stage('test div command') {
          try {
            sh '''
            sleep 5
            /usr/bin/test $(curl calculator-service.staging.svc.cluster.local:8080/div?a=6\\&b=2) -eq 3 && echo '6/2=3 - pass' || '6/2!=3 fail'
            DIVIDEBYZERO="$(curl calculator-service.staging.svc.cluster.local:8080/div?a=6\\&b=0)"
          
            if [ "$DIVIDEBYZERO" = "Division by 0" ]; then
              echo 'Divide by zero - pass'
            else
              echo "Divide by zero - fail - $DIVIDEBYZERO"
            fi
            '''
          } catch (Exception e) {
            echo 'div test failed - function not implemented'
          }
        }

      }

      container('cloud-sdk') {
        stage('Deploy to Prod - GKE') {
          sh '''
          echo 'namespaces in the staging environment'
          kubectl get ns
          gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud container clusters get-credentials umls23 --region us-east1 --project umls23-381716
          echo 'namespaces in the prod environment'
          kubectl get ns
          '''
        }
      }

      
    }
  }
}