podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    metadata:
      namespace: staging
    spec:
      containers:
      - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('Calculator Acceptance Testing') {
      git branch: 'main', url: 'https://github.com/jstmarie/week9.git'
      container('gradle') {

        stage('start calculator') {
            sh '''
            cd Ex1
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            ./kubectl apply -f calculator.yaml
            ./kubectl apply -f hazelcast.yaml
            '''
        }

      }
    }
  }
}