podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    metadata:
      namespace: staging
    spec:
      containers:
      - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('Calculator Acceptance Testing') {
      git branch: 'main', url: 'https://github.com/jstmarie/week9.git'
      container('gradle') {

        stage('start calculator') {
          sh '''
          cd Ex1
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          ./kubectl apply -f calculator.yaml
          ./kubectl apply -f hazelcast.yaml
          '''
        }

        stage('test div command') {
          sh '''
          /usr/bin/test $(curl calculator-service:8080/sum?a=6\\&b=2) -eq 8 && echo '6+2=8 - pass' || '6+2!=8 fail'
          /usr/bin/test $(curl calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo '6/2=3 - pass' || '6/2!=3 fail'

          DIVIDEBYZERO="$(curl calculator-service:8080/div?a=6\\&b=0)"
          
          if [ "$DIVIDEBYZERO" = "Division by 0" ]; then
            echo 'Divide by zero - pass'
          else
            echo "Divide by zero - fail - $DIVIDEBYZERO"
          fi
          '''
        }

      }
    }
  }
}